name: Deploy App to Firebase Distribution

on:
  pull_request:
    types:
      - opened

jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: run unit test
        run: ./gradlew testFreeDebugUnitTest

